# Generated by Django 6.0 on 2026-01-29 16:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quicktix", "0003_alter_user_country_passwordhistory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
